# Application Name
spring.application.name=transaction-monitoring

# Server Port
server.port=8080


# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/transaction_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=root

spring.datasource.password=n3u3da!


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# JSON Timezone
spring.jackson.time-zone=UTC


# Swagger Configuration
springdoc.api-docs.path=/api-docs

# Frontend CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

