import type { Alert, AuditEvent, InvestigationNote, Transaction } from '../models/alertModels'

export const mockAlert: Alert = {
  id: 1001,
  alertRef: 'ALT-1001',
  accountId: 'ACC-001',
  ruleId: 1,
  ruleName: 'Large Single Transaction',
  ruleType: 'AMOUNT_THRESHOLD',
  severity: 'HIGH',
  status: 'INVESTIGATING',
  message:
    'Transaction TXN-1001 had an amount of £15,500.00 which exceeded the configured threshold of £10,000.00.',
  createdAt: '2026-08-04T06:38:37Z',
  acknowledgedAt: '2026-08-04T07:00:00Z',
  investigatingAt: '2026-08-04T07:05:00Z',
  closedAt: null,
  dismissedAt: null,
}

export const mockTransactions: Transaction[] = [
  {
    id: 1001,
    transactionRef: 'TXN-1001',
    payeeId: 'PAYEE-GLOBAL-INC',
    payeeName: 'Global Inc.',
    amount: 15500,
    currency: 'GBP',
    type: 'DEBIT',
    occurredAt: '2026-08-04T06:38:37Z',
    status: 'FLAGGED',
    description: 'International wire transfer',
  },
]

export const mockNotes: InvestigationNote[] = [
  {
    id: 1,
    alertId: 1001,
    operatorName: 'Current User',
    content: 'Verified transaction details with customer.',
    createdAt: '2026-08-04T07:10:22Z',
  },
]

export const mockAuditHistory: AuditEvent[] = [
  {
    id: 1,
    alertId: 1001,
    eventType: 'ALERT_CREATED',
    description: 'Alert generated by AMOUNT_THRESHOLD rule',
    operatorName: null,
    occurredAt: '2026-08-04T06:38:37Z',
  },
  {
    id: 2,
    alertId: 1001,
    eventType: 'ALERT_ACKNOWLEDGED',
    description: 'Status changed from OPEN to ACKNOWLEDGED',
    operatorName: 'System',
    occurredAt: '2026-08-04T07:00:00Z',
  },
  {
    id: 3,
    alertId: 1001,
    eventType: 'ALERT_INVESTIGATING',
    description: 'Status changed from ACKNOWLEDGED to INVESTIGATING',
    operatorName: 'Current User',
    occurredAt: '2026-08-04T07:05:00Z',
  },
  {
    id: 4,
    alertId: 1001,
    eventType: 'NOTE_ADDED',
    description: 'Investigation note added by operator',
    operatorName: 'Current User',
    occurredAt: '2026-08-04T07:10:22Z',
  },
]

